apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-aiagent-ui
  namespace: k8s-aiagent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-aiagent-ui
  template:
    metadata:
      labels:
        app: k8s-aiagent-ui
    spec:
      containers:
      - name: k8s-aiagent-ui
        image: ${YOUR_REGISTRY}/k8s-aiagent-ui:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-aiagent-ui
  namespace: k8s-aiagent
spec:
  selector:
    app: k8s-aiagent-ui
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP          

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-aiagent-ingress
  namespace: k8s-aiagent
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: k8s-aiagent-ui.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-aiagent-ui
            port:
              number: 80