apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-aiagent-ui-ingress
  namespace: ops-agent
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.1.1/32,10.10.10.0/24"
    
spec:
  rules:
  - host: k8s-aiagent-ui.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-aiagent-ui
            port:
              number: 80
  # 添加后端API代理配置
  - host: k8s-aiagent-ui.lab
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: OpsAgent-service
            port:
              number: 8080 